apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: notejam-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/add-base-url: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/configuration-snippet: rewrite ^/grafana(.*) /$1;
spec:
  backend:
    serviceName: default-backend
    servicePort: 80
  rules:
  - host: notejam.jam
    http:
      paths:
       - backend:
            serviceName: grafana
            servicePort: 3000
         path: /grafana
       - backend:
            serviceName: kibana
            servicePort: 5601
         path: /app/kibana
       - backend:
            serviceName: jenkins
            servicePort: 8080
         path: /jenkins 
       - backend:
           serviceName: notejam-app-service
           servicePort: 3000