apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: notejam-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: notejam.jam
    http:
      paths:
       - backend:
           serviceName: notejam-app-service
           servicePort: 3000